### ISSUE TITLE
Way to search for anime by titles

### ISSUE THREAD

**Issue by rr-** [rachmadaniHaryono/python-mal#5]
Right now we can only query by IDs which isn't always useful.

**Comment by rachmadaniHaryono** [comment]
this is being implemented right now. the last commit contain search function but only for `all` mode. this is only simple search. the actual `anime` mode search can have multiple option. 

the example for this simple search can be found here.

https://github.com/rachmadaniHaryono/python-mal/blob/master/docs/getting_started.rst

expect `anime` mode search in next commit

**Comment by rachmadaniHaryono** [comment]
the simple search anime is on a4b9bb13d8b3cf9bb1ea5111cbd33e72b310e352

now it can be used either from using generic search or directly use the function. it return a generator instead of list, so it will not directly load all the search page.

```
>>> import myanimelist.session
>>> session = myanimelist.session.Session()
>>> session.search('beebop', mode='anime')
>>> # or
>>> res = session.search_anime('beebop')
```

**Comment by rr-** [comment]
Thanks. BTW is MAL still using Incapsula?

**Comment by rachmadaniHaryono** [comment]
i don't know. [this thread](https://myanimelist.net/forum/?topicid=685567&show=350) didn't mention that they are still using it. And as i never encounter any connection error when developing the package.
