### ISSUE TITLE
While parsing for Re:Zero I got this error

### ISSUE THREAD

**Issue by bppdddqqqq** [rachmadaniHaryono/python-mal#8]
Traceback (most recent call last):
  File "./crunch-dl.py", line 364, in <module>
    showname = unidecode(str(anime.alternative_titles['English'])[3:-2])
  File "/home/r3d_scorpion/Crunchyroll/myanimelist/base.py", line 86, in _decorator
    getattr(self, func_name)()
  File "/home/r3d_scorpion/Crunchyroll/myanimelist/media.py", line 705, in load
    self.set(self.parse(utilities.get_clean_dom(media_page), media_page_original))
  File "/home/r3d_scorpion/Crunchyroll/myanimelist/media.py", line 445, in parse
    media_info = self.parse_sidebar(media_page, media_page_original)
  File "/home/r3d_scorpion/Crunchyroll/myanimelist/anime.py", line 135, in parse_sidebar
    raise MalformedAnimePageError(self.id, None, message="Could not find title div")
myanimelist.anime.MalformedAnimePageError: Could not find title div
ID: 74697
HTML: None

**Comment by rachmadaniHaryono** [comment]
is it the correct link?

there is no anime `https://myanimelist.net/anime/74697` but re zero novel is actually on this link`https://myanimelist.net/manga/74697`

the actual rezero anime is on this link `https://myanimelist.net/anime/31240/Re_Zero_kara_Hajimeru_Isekai_Seikatsu` or these links

```
https://myanimelist.net/anime/33142/Re_Zero_kara_Hajimeru_Break_Time
https://myanimelist.net/anime/33569/Re_Petit_kara_Hajimeru_Isekai_Seikatsu
```

**Comment by rachmadaniHaryono** [comment]
hi @pleyar, is there any update?

**Comment by bppdddqqqq** [comment]
I have paused the progress for the implementation. But you were right. I was querying for the manga instead of anime.

**Comment by rachmadaniHaryono** [comment]
ok i understood. i will close this issue then. if you have another issue/feature request please open other issue. 

thanks
