### ISSUE TITLE
add video parsing and broadcast

### ISSUE THREAD

**Issue by rachmadaniHaryono** [rachmadaniHaryono/python-mal#9]
- [ ] video parsing
- [ ] anime broadcast

see from @pushrbx repo till this commit 
~~https://github.com/pushrbx/python3-mal/commit/ebeb327c6813d12ccbd67930fd6b4eec20cda2b1~~ 
https://github.com/pushrbx/python-mal/commit/9da2c33

**Comment by pushrbx** [comment]
Haven't you meant the pushrbx@9da2c33 commit?
I've screwed up the order of commits a bit, because I forgot to add an extra entry in the README.md.

**Comment by rachmadaniHaryono** [comment]
yes you are right, thank you

**Comment by rachmadaniHaryono** [comment]
merged with #12
